language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
# This is needed to get https://github.com/lektor/lektor/pull/240, which is
# currently unreleased. When that's released, we can move back to installing
# straight from pip
install:
  - pip install git+git://github.com/lektor/lektor.git@bb85c95d8dceb326dacca0a577ab81d999dd5297
  - npm install
script:
  - npm run build
  - lektor build
deploy:
  provider: script
  script: lektor deploy ghpages
  on:
    branch: master
